template: true
valuesFilePath: ./values.yml

resources:
  - name: monitor_git_trigger1
    type: GitRepo
    configuration:
      path: {{.jfrog-pipelines.sourceRepository}}
      gitProvider: git_int
pipelines:
  - name: testgit
    steps:
      - name: basic_first
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
      - name: basic{{$i}}
        type: Bash
        configuration:
          inputResources:
            - name: monitor_git_trigger1
              trigger: true
          inputSteps:
            - name: basic_first
        execution:
          onExecute:
            - echo hi
            - echo "shashank"
            - echo "testing commit 123"
            - update_commit_status monitor_git_trigger1 --message "Github Pipeline Success"
          onSuccess:
            - update_commit_status monitor_git_trigger1 --message "Github Pipeline Success"
